### ISSUE TITLE
公众号页面顶部tap栏滑动有问题

### ISSUE THREAD

**Issue by Quyunshuo** [ASCII13/WanAndroid#2]
公众号页面顶部tap栏滑动有问题，滑动时会反弹到原来的位置，tap切换很慢

**Comment by ASCII13** [comment]
请问：机型是什么？系统版本？

我这边 iPhone X，iPhone XR，iPhone 11 pro 都没有遇到这个问题

**Comment by Quyunshuo** [comment]
iPhone 7 Plus ios 13.5

**Comment by Quyunshuo** [comment]
刚刚又试了试  没有之前的那个问题了  只是页面切换了  tap跟随切换比较慢  大概有1点多秒才能切换过去

**Comment by ASCII13** [comment]
这个现象挺奇怪的，一直没遇到，我会尽力定位一下问题，感谢反馈。
